// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKrn6qy-gw5T2jnCaj6poW9NL4nkpsz4Y',
    appId: '1:760666366831:web:da5575c72b82e9afdafe9a',
    messagingSenderId: '760666366831',
    projectId: 'to-do-app-aa5d5',
    authDomain: 'to-do-app-aa5d5.firebaseapp.com',
    storageBucket: 'to-do-app-aa5d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBb6EDiPggCUQdMkR_ARWS-GovDrifqA0',
    appId: '1:760666366831:android:663e0142c6af2ce2dafe9a',
    messagingSenderId: '760666366831',
    projectId: 'to-do-app-aa5d5',
    storageBucket: 'to-do-app-aa5d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBJAtwazXVAGP2TIpaxzIiCplrL6AKBrk',
    appId: '1:760666366831:ios:d39031e9470f1067dafe9a',
    messagingSenderId: '760666366831',
    projectId: 'to-do-app-aa5d5',
    storageBucket: 'to-do-app-aa5d5.firebasestorage.app',
    iosBundleId: 'com.example.verrakiProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBJAtwazXVAGP2TIpaxzIiCplrL6AKBrk',
    appId: '1:760666366831:ios:d39031e9470f1067dafe9a',
    messagingSenderId: '760666366831',
    projectId: 'to-do-app-aa5d5',
    storageBucket: 'to-do-app-aa5d5.firebasestorage.app',
    iosBundleId: 'com.example.verrakiProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKrn6qy-gw5T2jnCaj6poW9NL4nkpsz4Y',
    appId: '1:760666366831:web:be3866b1f8f917b3dafe9a',
    messagingSenderId: '760666366831',
    projectId: 'to-do-app-aa5d5',
    authDomain: 'to-do-app-aa5d5.firebaseapp.com',
    storageBucket: 'to-do-app-aa5d5.firebasestorage.app',
  );
}
